### ISSUE TITLE
Error Translate Offine with a program

### ISSUE THREAD

**Issue by DarkVN101** [janvarev/OneRingTranslator#11]
Today I translated with OneRingTranslator with LunaTranslator from Japanese to Spanish and the text comes out in English.
Is there someone who uses that program who can help me with the configuration to translate from Japanese to Spanish
what I have to modify to make it work with the fb_nllb_translate translation model
(I once found a way to translate offline translation into Spanish with LunaTranslator but I don't remember I changed /: so it's possible)
Thanks in advance, it's something I'm trying to do because I know it's faster to translate online but it can be useful if my internet goes down.

**Comment by janvarev** [comment]
We can't adjust program on your computer due to this description
