### ISSUE TITLE
OpenAI no longer supported 

### ISSUE THREAD

**Issue by Jeffrey-Lang** [janvarev/OneRingTranslator#8]
You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

If i run the automated migrate after that the plugin wont init anymore.

Could anyone fix the plugin so it is compatible with the new version?

**Comment by janvarev** [comment]
Must be fixed in new version 7.6.0 - moved call to just POST request.
