### ISSUE TITLE
Translated text keep new lines <br>?

### ISSUE THREAD

**Issue by Jeffrey-Lang** [janvarev/OneRingTranslator#9]
Hey,

Is there a way to keep new lines / <br> in the translated text?

Or did i miss something?

**Comment by janvarev** [comment]
Keeping new lines depends on translator engine. As I know, Google Translate usually keeps them, but Deepl not. That's not an responsibility of core engine for now.

**Comment by Jeffrey-Lang** [comment]
@janvarev Thanks for the reply, as i was testing it i found out that if you use the offline translator we can replace newlines with <br>'s and that will keep the text nice with the offline engine!.

So for anyone who is facing this issue just regex new lines and replace them with <br> then if you do not want <br> but new lines reverse the regex the translator will keep the <br>.
